services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    ports:
      - '80:80'

  apache:
    build: ./apache
    volumes:
      - ./php:/var/www/html # Основной код проекта (папка php)
      #- ./apache/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shop_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # php:
  #   build:
  #     context: ./apache
  #   volumes:
  #     - ./php:/var/www/html # Основной код проекта (папка php)
  #   working_dir: /var/www/html/public # Устанавливаем рабочую директорию на папку public

  # composer:
  #   image: composer:latest
  #   volumes:
  #     - ./php:/app # Монтируем папку php для доступа к composer.json
  #   working_dir: /app # Устанавливаем рабочую директорию на папку php

volumes:
  db_data:
